# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-action


name: Generate Cypress Report
on:
  push:
    branches:
      - 'master'

jobs:
  cypress-test:
    name: Run on Chrome 83
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.0-chrome83-ff77
    steps:
      - uses: actions/checkout@v3
      
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          clean : npm cache clean --force
          build: npm run build
          start: npm start
